insert into collector_virtual_positions (accountid,
                                         positionuid,
                                         instrumentuid,
                                         figi,
                                         instrumenttype,
                                         quantity,
                                         averagepositionprice,
                                         expectedyield,
                                         expectedyieldfifo,
                                         expiredate,
                                         currentprice,
                                         averagepositionpricefifo)
values (:accountid,
        :positionuid,
        :instrumentuid,
        :figi,
        :instrumenttype,
        :quantity,
        :averagepositionprice,
        :expectedyield,
        :expectedyieldfifo,
        :expiredate,
        :currentprice,
        :averagepositionpricefifo)
on conflict (positionuid) do nothing;
