insert into collector_positions (accountid,
                                 figi,
                                 instrumenttype,
                                 quantity,
                                 averagepositionprice,
                                 expectedyield,
                                 currentnkd,
                                 currentprice,
                                 averagepositionpricefifo,
                                 blocked,
                                 blockedlots,
                                 positionuid,
                                 instrumentuid,
                                 varmargin,
                                 expectedyieldfifo)
values (:accountid,
        :figi,
        :instrumenttype,
        :quantity,
        :averagepositionprice,
        :expectedyield,
        :currentnkd,
        :currentprice,
        :averagepositionpricefifo,
        :blocked,
        :blockedlots,
        :positionuid,
        :instrumentuid,
        :varmargin,
        :expectedyieldfifo)
on conflict (positionuid) do nothing;
